// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjfFn-Nq4g8EELUbrZEHVYGsBy2Ss8E_A',
    appId: '1:660096522423:web:7198b62fdea54f59a1d532',
    messagingSenderId: '660096522423',
    projectId: 'ekanisa',
    authDomain: 'ekanisa.firebaseapp.com',
    storageBucket: 'ekanisa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsoJCfYzNB-tb1shULkdEH-cXT4C0a6LI',
    appId: '1:660096522423:android:d97169a5a766ea17a1d532',
    messagingSenderId: '660096522423',
    projectId: 'ekanisa',
    storageBucket: 'ekanisa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRcDAju3Y3iXYvSVNI_2PaAhTtnX-4UNE',
    appId: '1:660096522423:ios:79e39cc3721cd386a1d532',
    messagingSenderId: '660096522423',
    projectId: 'ekanisa',
    storageBucket: 'ekanisa.appspot.com',
    iosBundleId: 'com.example.ekanisa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRcDAju3Y3iXYvSVNI_2PaAhTtnX-4UNE',
    appId: '1:660096522423:ios:8e3cb559f73c1f56a1d532',
    messagingSenderId: '660096522423',
    projectId: 'ekanisa',
    storageBucket: 'ekanisa.appspot.com',
    iosBundleId: 'com.example.ekanisa.RunnerTests',
  );
}
